export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"
export const GET_USER = "GET_USER"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const API_ERROR = "LOGIN_API_ERROR"
export const API_ERROR_NULL = "LOGIN_API_ERROR_NULL"


export const LOGOUT = "LOGOUT"
export const Regsiter_User = "Regsiter_User"