export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const API_ERROR = "LOGIN_API_ERROR"

export const USER_FROM_LOCALSTORAGE = 'USER_FROM_LOCALSTORAGE'

export const LOGOUT = "LOGOUT"
export const Regsiter_User = "Regsiter_User"